config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from coraka.users.views import consent, subscribe

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("firm/", TemplateView.as_view(template_name="pages/firm.html"), name="firm"),
    path("network/", TemplateView.as_view(template_name="pages/career.html"), name="career"),
    path("portfolio/", TemplateView.as_view(template_name="pages/portfolio.html"), name="portfolio"),
    path(
        "contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"
    ),
    path('consent', consent, name='consent'),
    path('subscribe', subscribe, name='subscribe'),
    # Django Admin, use {% url 'admin:index' %}
    path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    path(
        "jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")
    ),  # Django JET dashboard URLS
    path("admin/", include("admin_honeypot.urls", "admin_honeypot")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

coraka/users/urls.py
from django.urls import path

from coraka.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

coraka/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import (
    CASCADE,
    DO_NOTHING,
    BooleanField,
    CharField,
    DateField,
    EmailField,
    DecimalField,
    URLField,
    DateTimeField,
    FloatField,
    SlugField,
    TextField,
    TimeField,
    IntegerField,
    PositiveSmallIntegerField,
    PositiveBigIntegerField,
    ForeignKey,
    ManyToManyField,
    OneToOneField,
    GenericIPAddressField,
    Sum
)
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from model_utils.models import TimeStampedModel
from tinymce.models import HTMLField

class User(AbstractUser):
    """
    Default custom user model for coraka.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

class Subscribe(TimeStampedModel):
    email = EmailField(blank=False)

    def __str__(self):
        return self.email
    
class Consent(TimeStampedModel):
    ipAddress = CharField(max_length=255, blank=True)
    consented = BooleanField(default=False)

    def __str__(self):
        return self.ipAddress

    class Meta:
        managed = True
        verbose_name = "Consent"
        verbose_name_plural = "Consents"
        ordering = ["-modified"]

class Porttfolio(TimeStampedModel):
    logo = URLField(blank=False)
    name = CharField(max_length=255)
    service = CharField(max_length=255)
    sector = CharField(max_length=255)
    website = URLField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        verbose_name = "Portfolio"
        verbose_name_plural = "Portfolios"
        ordering = ["-modified"]


class Career(TimeStampedModel):
    logo = URLField(blank=False, default="https://panteracapital.com/wp-content/uploads/2022/10/Logo-2.png")
    title = CharField(max_length=500)
    description = HTMLField()
    requirements = HTMLField()
    salary = DecimalField(default=0.00, decimal_places=2, max_digits=20)
    application_email = EmailField(blank=False)

    active = BooleanField(default=True)

    def __str__(self) -> str:
        return self.title.title()

    class Meta:
        managed = True
        verbose_name = "Careers"
        verbose_name_plural = "Careers"
        ordering = ["-modified"]

coraka/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

coraka/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.http import HttpResponseRedirect

from .models import Consent, Subscribe
User = get_user_model()

def subscribe(request):
    if request.method == 'POST':
        mail = request.POST.get('mail')
        Subscribe.objects.create(email=mail)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return render(request, 'pages/subscribe.html')

def consent(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')

    Consent.objects.create(ipAddress=ip, consented=True)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

coraka/templates/base.html
{% load static i18n webpack_loader %}

<!DOCTYPE html>

{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% get_language_info_list for LANGUAGES as languages %}

<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <title>{% block title %}Coraka — {% endblock title %}</title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Forex trading security and Asset management firm">
    <meta name="author" content="Darkcodr Codes">
    <meta name="viewport" content="width=device-width,viewport-fit=cover,initial-scale=1,minimum-scale=1,maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="format-detection" content="telephone=yes">
    <meta name="format-detection" content="email=no">
    <meta name="full-screen" content="yes">
    <meta name="x5-fullscreen" content="true">
    <meta name="360-fullscreen" content="true">
    <meta name="screen-orientation" content="portrait">
    <meta name="x5-orientation" content="portrait">
    <meta name="renderer" content="webkit">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="320">
    <meta name="browsermode" content="application">
    <meta name="x5-page-mode" content="app">
    <meta name="msapplication-tap-highlight" content="no">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta http-equiv="x-dns-prefetch-control" content="on">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="Classification" content="Service">
    <meta name="category" content="Fintech">
    <meta name="coverage" content="Worldwide">
    <meta name="distribution" content="Global">

    <link rel="icon" href="{% static 'vendors/images/logo.png' %}">
    <link rel="dns-prefetch" href="https://coraka.com">
    <link rel="dns-prefetch" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300&&family=DynaPuff:wght@400;500;600;700&family=Be+Vietnam+Pro:wght@100;200;300;400;500;600;700;800;900&family=Poiret+One&family=Raleway:ital,wght@0,100;0,200;0,300;0,500;0,600;0,700;0,800;1,100;1,200&family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0&display=swap" rel="stylesheet">
    <link rel="shortlink" href="https://coraka.com">


    {% block css %}
    {% endblock %}

    {% block javascript %}
    {% endblock javascript %}

    {% stylesheet_pack 'app' %}
  </head>

  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' style="background-image: url({% static 'vendors/images/bg.jpg' %}); background-size: fit; background-repeat background-position: top">

    {% include "snippets/navbar.html" %}

    <main class="w-screen min-h-screen pt-24">
      {% block content %}{% endblock content %}
    </main>

    {% block modal %}
    <!-- Put this part before </body> tag -->
    <input type="checkbox" id="modal" class="modal-toggle" />
    <label for="modal" class="modal cursor-pointer">
      <label class="modal-box relative" for="">
        <h3 class="text-lg font-bold">Congratulations random Internet user!</h3>
        <p class="py-4">You've been selected for a chance to get one year of subscription to use Wikipedia for free!</p>
      </label>
    </label>
    {% endblock modal %}

    {% include "snippets/footer.html" %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}

    {% javascript_pack 'app' %}
    <script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
      }
    </script>

    <script>
      window.ip = '{{ip}}'
    </script>

    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
  </body>
</html>

coraka/templates/pages/career.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} Join Our Network
{% endblock title %}

{% block content %}
<section class="py-24 px-4 md:px-44 xl:px-64">
  <div class="w-full md:max-w-2xl md:mx-auto text-center space-y-4">
    <h4 class="text-3xl md:text-5xl font-bold">Work with the leading companies in the blockchain industry</h4>
    <p>Tell us about your professional DNA to get discovered by any company in our network with opportunities relevant to your career goals.</p>
  </div>
</section>

<section class="px-4 md:px-44 xl:px-64 py-6">

  <div class="overflow-x-auto relative shadow-md">
    <table class="text-center w-full text-sm text-left text-dark dark:text-blue-100">
      <thead class="text-base text-dark uppercase bg-light border-b border-success dark:text-white">
        <tr>
          <th scope="col" class="py-3 px-6">
            COMPANY
          </th>
          <th scope="col" class="py-3 px-6">
            SALARY
          </th>
          <th scope="col-2" class="py-3 px-6">
            DESCRIPTION/ROLE
          </th>
          <th scope="col" class="py-3 px-6">
            ACTION
          </th>
        </tr>
      </thead>
      <tbody>
        {% for object in careers %}
        <tr class="bg-white border-b border-success hover:bg-success hover:text-dark ">
          <th scope="row" class="py-4 px-6 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100">
            <img src="{{object.logo}}" alt="" class="h-10">
          </th>
          <td class="py-4 px-6">
            {{object.salary}}
          </td>
          <td class="py-4 px-6 text-sm space-y-3">
            <strong class="text-2xl font-bold uppercase block">{{object.title}}</strong>
            <div class="text-justify line-clamp-3">{{object.description}}</div>
          </td>
          <td class="py-4 px-6">
            <a href="mailto://{{object.application_email}}"
              class="font-medium text-dark hover:border-dark hover:border-2 hover:text-dark duration-300 py-3 px-5">APPLY BY MAIL</a>
          </td>
        </tr>
        {% empty %}
        <tr class="bg-white border-b border-success hover:bg-success hover:text-dark ">
          <th scope="row" class="flex-none py-4 px-6 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100">
            <img src="https://panteracapital.com/wp-content/uploads/2022/10/Logo-2.png" alt="" class="h-10">
          </th>
          <td class="py-4 px-6">
            $170,000 Annually
          </td>
          <td class="py-4 px-6 space-y-3">
            <strong class="text-2xl font-bold uppercase">software engineer</strong>
            <div class="text-justify line-clamp-3">{% lorem 3 %}</div>
          </td>
          <td class="py-4 px-6">
            <a href="#"
              class="font-medium text-dark hover:border-dark hover:border-2 hover:text-dark duration-300 py-3 px-5">APPLY</a>
          </td>
        </tr>
        <tr class="bg-white border-b border-success hover:bg-success hover:text-dark ">
          <th scope="row" class="flex-none py-4 px-6 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100">
            <img src="https://panteracapital.com/wp-content/uploads/2021/02/Alchemy-logo.svg" alt="" class="h-10">
          </th>
          <td class="py-4 px-6">
            $170,000 Annually
          </td>
          <td class="py-4 px-6 space-y-3">
            <strong class="text-2xl font-bold uppercase">software engineer</strong>
            <div class="text-justify line-clamp-3">{% lorem 3 %}</div>
          </td>
          <td class="py-4 px-6">
            <a href="#"
              class="font-medium text-dark hover:border-dark hover:border-2 hover:text-dark duration-300 py-3 px-5">APPLY</a>
          </td>
        </tr>
        <tr class="bg-white border-b border-success hover:bg-success hover:text-dark ">
          <th scope="row" class="flex-none py-4 px-6 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100">
            <img src="https://panteracapital.com/wp-content/uploads/2021/02/abra-logo.svg" alt="" class="h-10">
          </th>
          <td class="py-4 px-6">
            $170,000 Annually
          </td>
          <td class="py-4 px-6 space-y-3">
            <strong class="text-2xl font-bold uppercase">software engineer</strong>
            <div class="text-justify line-clamp-3">{% lorem 3 %}</div>
          </td>
          <td class="py-4 px-6">
            <a href="#"
              class="font-medium text-dark hover:border-dark hover:border-2 hover:text-dark duration-300 py-3 px-5">APPLY</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endblock content %}

coraka/templates/pages/contact.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} Contact Us
{% endblock title %}

{% block content %}
<section class="w-screen px-4 md:px-44 xl:px-64 py-24">
  <h1 class="text-3xl md:text-5xl font-bold text-center">Contact Us</h1>

  <div class="py-24 grid grid-cols-1 md:grid-cols-3 gap-4">
    <div class="space-y-24">
      <div class="space-y-4">
        <strong class="border-b-2 border-b-dark py-4 w-full block text-2xl text-4xl">Phone</strong>
        <button class="border-2 border-dark hover:bg-dark hover:text-white py-3 px-5 duration-300">+1 789 8766 8746</button>
      </div>
      <div class="space-y-4">
        <strong class="border-b-2 border-b-dark py-4 w-full block text-2xl text-4xl">Social</strong>
        <div class="flex items-center space-x-10">
          <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 496 512" class="h-14 text-dark cursor-pointer hover:text-success duration-300"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M248,8C111.033,8,0,119.033,0,256S111.033,504,248,504,496,392.967,496,256,384.967,8,248,8ZM362.952,176.66c-3.732,39.215-19.881,134.378-28.1,178.3-3.476,18.584-10.322,24.816-16.948,25.425-14.4,1.326-25.338-9.517-39.287-18.661-21.827-14.308-34.158-23.215-55.346-37.177-24.485-16.135-8.612-25,5.342-39.5,3.652-3.793,67.107-61.51,68.335-66.746.153-.655.3-3.1-1.154-4.384s-3.59-.849-5.135-.5q-3.283.746-104.608,69.142-14.845,10.194-26.894,9.934c-8.855-.191-25.888-5.006-38.551-9.123-15.531-5.048-27.875-7.717-26.8-16.291q.84-6.7,18.45-13.7,108.446-47.248,144.628-62.3c68.872-28.647,83.183-33.623,92.511-33.789,2.052-.034,6.639.474,9.61,2.885a10.452,10.452,0,0,1,3.53,6.716A43.765,43.765,0,0,1,362.952,176.66Z"/></svg>

        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 448 512" class="h-14 text-dark cursor-pointer hover:text-success duration-300"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"/></svg>

        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 512 512" class="h-14 text-dark cursor-pointer hover:text-success duration-300"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>
        </div>
      </div>
    </div>

    <div class="space-y-4">
      <strong class="border-b-2 border-b-dark py-4 w-full block text-2xl text-4xl">Email</strong>

      <div class="space-y-2">
        <strong class="text-lg uppercase">asset recovery and inquiries</strong>
        <p>
          You can email our Coraka Recovery Team at: <a href="mailto://recovery@coraka.com" class="hover:text-bold hover:text-success hover:text-underline duration-300">recovery@coraka.com</a>
        </p>
      </div>

      <div class="space-y-2">
        <strong class="text-lg uppercase">investment advisory</strong>
        <p>
          You can email our Investment Advisory Team at: <a href="mailto://advisory@coraka.com" class="hover:text-bold hover:text-success hover:text-underline duration-300">advisory@coraka.com</a>
        </p>
      </div>

      <div class="space-y-2">
        <strong class="text-lg uppercase">data providers</strong>
        <p>
          We’re always looking for more data to make better predictions. If you have a dataset you think we should consider, shoot us an email: <a href="mailto://darrel@coraka.com" class="hover:text-bold hover:text-success hover:text-underline duration-300">darrel@coraka.com</a>
        </p>
      </div>
    </div>

    <div class="space-y-4">
      <strong class="border-b-2 border-b-dark py-4 w-full block text-2xl text-4xl">Locations</strong>

      <strong class="uppercase text-lg block">Dubai</strong>
      <strong class="uppercase text-lg block">Ghana</strong>
      <strong class="uppercase text-lg block">Nigeria</strong>
      <strong class="uppercase text-lg block">South Africa</strong>
    </div>
  </div>
</section>

{% endblock content %}

coraka/templates/pages/subscribe.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} Contact Us
{% endblock title %}

{% block content %}
<section class="w-screen px-4 md:px-44 xl:px-64 py-24">
  <div class="grid md:grid-cols-2 grid-cols-1 gap-5">
    <div class="space-y-4">
      <h1 class="text-2xl md:text-4xl font-bold">Coraka News Subscription</h1>
      <p>
        Stay updated with our latest news and crypto trends by subscribing to our new update channel
      </p>
    </div>
    <div>
      <form action="{% url 'subscribe' %}" class="space-y-">
        {% csrf_token %}
        <input type="email" name="mail">
      </form>
    </div>
  </div>
</section>
{% endblock content %}

coraka/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

coraka/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}